### ISSUE TITLE
Reset Value (menu option) does not do anything on sliders with constant initial values

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_viz#211]

**Comment by jgosmann** [comment]
At the moment it is not really a value reset, but just gives the control back to node function. Not sure what behavior we actually want (and to what value should the slider reset? the initial one in the config file? the one at build time?).

But if we do not change the functionality, we should change the name of the menu entry because it is definitely misleading.

**Comment by tcstewar** [comment]
It should go back to the initialized value, which is already being passed in to the slider constructor (```args.start_value```).

**Comment by cchan987** [comment]
> (and to what value should the slider reset? the initial one in the config file? the one at build time?).

unless this changed i am pretty sure the config file is not storing the slider values, it is only set at build time

**Comment by tcstewar** [comment]
> i am pretty sure the config file is not storing the slider values,

You're right.  And I'm pretty sure we don't want the config file to store slider values.  The ```args.start_value``` works fine.
