### ISSUE TITLE
Shutdown with double Ctrl+C

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_viz#234]
An IPython notebook server can be shut down by pressing Ctrl+C twice (in addition to Ctrl+C, y, enter). Doing this with nengo_viz just kills the server without shutting it down properly.

**Comment by hunse** [comment]
No, it should kill it properly. Originally I had code in to catch the second interrupt and print a nice message, but I got rid of that since either way the sever shutdown is in the outside `finally` block so it will happen no matter what.

It might be possible that someone presses Ctrl+C three times in quick succession, sending another interrupt while the server is shutting down, but I'm not sure what to do about that or if it's that likely (the server shutdown shouldn't take more than ~0.25 seconds).

**Comment by jgosmann** [comment]
I missed the shutdown message because of the exception traceback that will be thrown. I would be nice to suppress that.

[Here's the IPython notebook implementation btw.](https://github.com/ipython/ipython/blob/rel-3.1.0/IPython/html/notebookapp.py#L911) They register signal handlers which might be a slightly better approach on Unix, but apparently does not work on Windows ... (but I haven't checked the shutdown behavior on Windows).

**Comment by hunse** [comment]
If you don't want to see the traceback, you could press `Ctrl+C y <enter>` :smile:

I'd be fine adding the extra code for catching the second Ctrl+C back in. It makes the whole block a bit more confusing, but I think it's worth it.

**Comment by jgosmann** [comment]
But twice `Ctrl+C` is so much more efficient. :dash:
